# syntax=docker/dockerfile:1

# Alpine is chosen for its small footprint
# compared to Ubuntu
FROM golang:1.18 AS build

# Creating a working directory 
WORKDIR /app

# Downloading deps
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Copying all go files
COPY *.go ./

# Building go
RUN CGO_ENABLED=0 go build main.go


## Deploy
FROM gcr.io/distroless/static-debian11

WORKDIR /app

COPY --from=build /app/main main

EXPOSE 9090

CMD ["./main"]
